'use client';

import { startTransition, useEffect, useMemo, useRef, useState } from 'react';
import { Check, ChevronDown, Copy, Droplet, Eye, GripVertical, Plus, RefreshCw, Save, Sparkles, Trash2, WandSparkles } from 'lucide-react';

type Stop = { id: number; color: string; position: number };
type Mode = 'solid' | 'linear' | 'radial';
const initialStops: Stop[] = [{ id: 1, color: '#5B5FEF', position: 0 }, { id: 2, color: '#F36BA8', position: 100 }];

function hexToRgb(hex: string) { const value = hex.replace('#', '').padEnd(6, '0'); const number = parseInt(value, 16); return { r: number >> 16 & 255, g: number >> 8 & 255, b: number & 255 }; }
function rgbToHsl({ r, g, b }: { r: number; g: number; b: number }) { r /= 255; g /= 255; b /= 255; const max = Math.max(r, g, b), min = Math.min(r, g, b), light = (max + min) / 2; if (max === min) return { h: 0, s: 0, l: Math.round(light * 100) }; const d = max - min, saturation = light > .5 ? d / (2 - max - min) : d / (max + min); let hue = 0; if (max === r) hue = (g - b) / d + (g < b ? 6 : 0); else if (max === g) hue = (b - r) / d + 2; else hue = (r - g) / d + 4; return { h: Math.round(hue * 60), s: Math.round(saturation * 100), l: Math.round(light * 100) }; }
function hslToHex(h: number, s: number, l: number) { s /= 100; l /= 100; const chroma = (1 - Math.abs(2 * l - 1)) * s, x = chroma * (1 - Math.abs((h / 60) % 2 - 1)), m = l - chroma / 2; const [r, g, b] = h < 60 ? [chroma, x, 0] : h < 120 ? [x, chroma, 0] : h < 180 ? [0, chroma, x] : h < 240 ? [0, x, chroma] : h < 300 ? [x, 0, chroma] : [chroma, 0, x]; return `#${[r, g, b].map((value) => Math.round((value + m) * 255).toString(16).padStart(2, '0')).join('').toUpperCase()}`; }
function luminance(hex: string) { const values = Object.values(hexToRgb(hex)).map((value) => value / 255).map((value) => value <= .03928 ? value / 12.92 : ((value + .055) / 1.055) ** 2.4); return .2126 * values[0] + .7152 * values[1] + .0722 * values[2]; }
function contrast(hex: string, other: string) { const a = luminance(hex), b = other === '#fff' ? 1 : 0; return ((Math.max(a, b) + .05) / (Math.min(a, b) + .05)).toFixed(2); }

export default function Home() {
  const [color, setColor] = useState('#5B5FEF'); const [alpha, setAlpha] = useState(100); const [mode, setMode] = useState<Mode>('linear'); const [stops, setStops] = useState(initialStops); const [selectedId, setSelectedId] = useState(1); const [angle, setAngle] = useState(135); const [applyTo, setApplyTo] = useState('button'); const [presets, setPresets] = useState<{ name: string; value: string }[]>([]); const [recent, setRecent] = useState<string[]>([]); const [copied, setCopied] = useState(''); const pickerRef = useRef<HTMLDivElement>(null);
  const rgb = useMemo(() => hexToRgb(color), [color]); const hsl = useMemo(() => rgbToHsl(rgb), [rgb]); const selected = stops.find((stop) => stop.id === selectedId) ?? stops[0];
  const cssValue = mode === 'solid' ? color : mode === 'linear' ? `linear-gradient(${angle}deg, ${stops.map((stop) => `${stop.color} ${stop.position}%`).join(', ')})` : `radial-gradient(circle at 50% 50%, ${stops.map((stop) => `${stop.color} ${stop.position}%`).join(', ')})`;
  const updateColor = (value: string) => { if (/^#[0-9a-f]{6}$/i.test(value)) { setColor(value.toUpperCase()); setStops((items) => items.map((stop) => stop.id === selectedId ? { ...stop, color: value.toUpperCase() } : stop)); } };
  const copy = (value: string, key: string) => { navigator.clipboard?.writeText(value); setCopied(key); setTimeout(() => setCopied(''), 1400); };
  const randomColor = () => { const value = `#${Math.floor(Math.random() * 0xffffff).toString(16).padStart(6, '0')}`; updateColor(value); setRecent((items) => [value.toUpperCase(), ...items.filter((item) => item !== value.toUpperCase())].slice(0, 10)); };
  const randomGradient = () => { const palettes = [['#F97316', '#F43F5E'], ['#06B6D4', '#2563EB'], ['#8B5CF6', '#EC4899'], ['#22C55E', '#14B8A6']]; const palette = palettes[Math.floor(Math.random() * palettes.length)]; setStops(palette.map((item, index) => ({ id: index + 1, color: item, position: index * 100 }))); setSelectedId(1); setAngle(Math.floor(Math.random() * 260) + 40); setMode('linear'); };
  const addStop = () => { const id = Date.now(); setStops((items) => [...items, { id, color, position: 50 }].sort((a, b) => a.position - b.position)); setSelectedId(id); };
  const reset = () => { setColor('#5B5FEF'); setStops(initialStops); setSelectedId(1); setAngle(135); setMode('linear'); setApplyTo('button'); };
  useEffect(() => { const savedPresets = JSON.parse(localStorage.getItem('color-studio-presets') || '[]'); const savedRecent = JSON.parse(localStorage.getItem('color-studio-recent') || '[]'); startTransition(() => { setPresets(savedPresets); setRecent(savedRecent); }); }, []); useEffect(() => { localStorage.setItem('color-studio-presets', JSON.stringify(presets)); }, [presets]); useEffect(() => { localStorage.setItem('color-studio-recent', JSON.stringify(recent)); }, [recent]);
  const moveStop = (event: React.MouseEvent) => { if (!pickerRef.current || !selected) return; const box = pickerRef.current.getBoundingClientRect(); const position = Math.max(0, Math.min(100, ((event.clientX - box.left) / box.width) * 100)); setStops((items) => items.map((stop) => stop.id === selectedId ? { ...stop, position } : stop)); };
  const boardStyle = applyTo === 'background' ? { background: cssValue } : {}; const boardButton = applyTo === 'button' || applyTo === 'accent' ? { background: cssValue } : {}; const boardText = applyTo === 'text' ? { color } : {}; const boardCard = applyTo === 'card' ? { background: cssValue, color: '#fff' } : {}; const boardBorder = applyTo === 'border' ? { borderColor: color } : {};

  return <main className="app">
    <header><div className="brand"><span className="brand-mark"><Droplet size={16} /></span><strong>Color Studio</strong></div><div className="workspace-context"><span className="context-dot" /> Personal workspace <span className="context-divider">/</span> Untitled system</div><div className="header-actions"><button onClick={reset} className="nav-action"><RefreshCw size={14} /> Reset</button><button onClick={randomColor} className="nav-action"><Sparkles size={14} /> Random color</button><button onClick={randomGradient} className="nav-action"><RefreshCw size={14} /> Random gradient</button><button onClick={() => document.querySelector('.utility-section')?.scrollIntoView({ behavior: 'smooth' })} className="saved-action"><Save size={14} /> Saved</button></div></header>
    <section className="intro"><div><p className="eyebrow">COLOR EXPLORATION / 01</p><h1>Make color<br /><em>feel intentional.</em></h1></div><p className="intro-copy">A quiet space to find the exact shade, build a gradient, and see how it behaves in a real interface.</p></section>
    <div className="workspace">
      <aside className="panel controls"><div className="panel-heading"><div><span className="kicker">01 / COLOR</span><h2>Color controls</h2></div><button className="icon-button small" onClick={randomColor} aria-label="Random color"><WandSparkles size={15} /></button></div>
        <div className="picker" ref={pickerRef} style={{ background: `linear-gradient(to top, #000, transparent), linear-gradient(to right, #fff, transparent), hsl(${hsl.h}, 100%, 50%)` }} onClick={(event) => { const box = pickerRef.current!.getBoundingClientRect(); const saturation = Math.round(((event.clientX - box.left) / box.width) * 100); const lightness = Math.round(100 - ((event.clientY - box.top) / box.height) * 100); updateColor(hslToHex(hsl.h, saturation, lightness)); }}><span className="picker-dot" style={{ left: `${hsl.s}%`, top: `${100 - hsl.l}%`, background: color }} /></div>
        <label className="range-label">Hue <output>{hsl.h}°</output></label><input className="hue-range" type="range" min="0" max="360" value={hsl.h} onChange={(event) => updateColor(hslToHex(Number(event.target.value), hsl.s, hsl.l))} />
        <label className="range-label">Opacity <output>{alpha}%</output></label><input type="range" min="0" max="100" value={alpha} onChange={(event) => setAlpha(Number(event.target.value))} />
        <div className="input-grid"><label>HEX <div className="input-row"><span className="swatch" style={{ background: color }} /><input value={color} onChange={(event) => updateColor(event.target.value)} /><button onClick={() => copy(color, 'hex')}><Copy size={13} /></button></div></label><label>RGB <div className="value-input">{rgb.r}, {rgb.g}, {rgb.b}<button onClick={() => copy(`${rgb.r}, ${rgb.g}, ${rgb.b}`, 'rgb')}><Copy size={13} /></button></div></label><label>HSL <div className="value-input">{hsl.h}°, {hsl.s}%, {hsl.l}%<button onClick={() => copy(`${hsl.h}°, ${hsl.s}%, ${hsl.l}%`, 'hsl')}><Copy size={13} /></button></div></label></div>
        <div className="control-actions"><button className="outline-button" onClick={() => document.querySelector<HTMLInputElement>('#native-picker')?.click()}><Eye size={14} /> Pick from screen</button><input id="native-picker" hidden type="color" value={color} onChange={(event) => updateColor(event.target.value)} /><button className="outline-button" onClick={randomColor}><Sparkles size={14} /> Random</button></div>
      </aside>
      <section className="panel editor"><div className="panel-heading"><div><span className="kicker">02 / PLAYGROUND</span><h2>Gradient editor</h2></div><button className="outline-button" onClick={randomGradient}><RefreshCw size={14} /> Random gradient</button></div><div className="gradient-preview" style={{ background: cssValue }}><span>{mode === 'solid' ? 'SOLID COLOR' : mode === 'linear' ? 'LINEAR GRADIENT' : 'RADIAL GRADIENT'}</span></div>
        <div className="mode-switch">{(['solid', 'linear', 'radial'] as Mode[]).map((item) => <button key={item} className={mode === item ? 'selected' : ''} onClick={() => setMode(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div>
        {mode === 'linear' && <div className="angle-control"><label className="range-label">Angle <output>{angle}°</output></label><input type="range" min="0" max="360" value={angle} onChange={(event) => setAngle(Number(event.target.value))} /></div>}
        <div className="stop-header"><span>Gradient stops</span><button className="text-button" onClick={addStop}><Plus size={14} /> Add stop</button></div><div className="stop-track" onClick={moveStop} style={{ background: `linear-gradient(90deg, ${stops.map((stop) => `${stop.color} ${stop.position}%`).join(', ')})` }}>{stops.map((stop) => <button key={stop.id} className={`stop-handle ${selectedId === stop.id ? 'selected' : ''}`} style={{ left: `${stop.position}%`, background: stop.color }} onClick={(event) => { event.stopPropagation(); setSelectedId(stop.id); setColor(stop.color); }} aria-label={`Select stop ${stop.position}%`} />)}</div>
        <div className="stop-list">{stops.map((stop, index) => <div className={`stop-row ${selectedId === stop.id ? 'current' : ''}`} key={stop.id} onClick={() => { setSelectedId(stop.id); setColor(stop.color); }}><GripVertical size={15} className="grip" /><span className="swatch" style={{ background: stop.color }} /><div><strong>Stop {index + 1}</strong><small>{stop.color}</small></div><label><input type="number" min="0" max="100" value={Math.round(stop.position)} onChange={(event) => setStops((items) => items.map((item) => item.id === stop.id ? { ...item, position: Number(event.target.value) } : item))} />%</label>{stops.length > 2 && <button className="delete-button" onClick={() => setStops((items) => items.filter((item) => item.id !== stop.id))}><Trash2 size={14} /></button>}</div>)}</div>
      </section>
      <aside className="panel preview-panel"><div className="panel-heading"><div><span className="kicker">03 / APPLICATION</span><h2>Test board</h2></div><span className="live"><span /> Live</span></div><div className="board" style={boardStyle}><div className="board-nav"><span className="mini-logo">✦</span><span className="mini-lines" /></div><div className="board-content"><span className="badge" style={boardButton}>New collection</span><h3 style={boardText}>Design that makes<br />a quiet impression.</h3><p>Thoughtful tools for people who care about the details.</p><button className="board-cta" style={boardButton}>Get started <span>↗</span></button><div className="sample-card" style={{ ...boardCard, ...boardBorder }}><div className="card-dot" style={boardButton} /><div><strong>Color system</strong><small>Everything in its place.</small></div><span className="card-arrow">→</span></div></div></div><label className="apply-label">Apply selected <span>{selected?.color}</span></label><div className="apply-grid">{['background', 'button', 'card', 'text', 'border', 'accent'].map((item) => <button key={item} className={applyTo === item ? 'selected' : ''} onClick={() => setApplyTo(item)}>{item}</button>)}</div></aside>
    </div>
    <section className="lower-grid"><div className="panel css-panel"><div className="panel-heading"><div><span className="kicker">OUTPUT</span><h2>CSS value</h2></div><button className="copy-button" onClick={() => copy(`background: ${cssValue};`, 'css')}>{copied === 'css' ? <><Check size={14} /> Copied</> : <><Copy size={14} /> Copy CSS</>}</button></div><pre><span>.gradient</span> {'{'}{`\n  background: ${cssValue};\n`}{'}'}</pre><div className="quick-copy"><button onClick={() => copy(color, 'hex2')}>Copy HEX</button><button onClick={() => copy(`${rgb.r}, ${rgb.g}, ${rgb.b}`, 'rgb2')}>Copy RGB</button><button onClick={() => copy(`${hsl.h}°, ${hsl.s}%, ${hsl.l}%`, 'hsl2')}>Copy HSL</button></div></div><div className="panel info-panel"><div className="panel-heading"><div><span className="kicker">ANALYSIS</span><h2>Color information</h2></div></div><div className="info-color"><span className="swatch large" style={{ background: color }} /><div><strong>{color}</strong><small>Selected color</small></div><span className="opacity">{alpha}% opacity</span></div><div className="contrast-grid"><div><small>On white</small><strong>{contrast(color, '#fff')}:1</strong><span className={Number(contrast(color, '#fff')) >= 4.5 ? 'pass' : 'fail'}>{Number(contrast(color, '#fff')) >= 4.5 ? '✓ AA pass' : '× AA fail'}</span></div><div><small>On black</small><strong>{contrast(color, '#000')}:1</strong><span className={Number(contrast(color, '#000')) >= 4.5 ? 'pass' : 'fail'}>{Number(contrast(color, '#000')) >= 4.5 ? '✓ AA pass' : '× AA fail'}</span></div></div></div></section>
    <section className="utility-section"><div className="section-title"><div><span className="kicker">YOUR LIBRARY</span><h2>Presets & palette</h2></div><button className="save-button" onClick={() => setPresets((items) => [...items, { name: `Untitled ${items.length + 1}`, value: cssValue }])}><Save size={15} /> Save preset</button></div><div className="preset-row">{presets.length ? presets.map((preset, index) => <div className="preset" key={`${preset.name}-${index}`}><div className="preset-color" style={{ background: preset.value }} /><strong>{preset.name}</strong><small>{preset.value}</small><button onClick={() => { setMode(preset.value.startsWith('linear') ? 'linear' : 'solid'); setColor(preset.value.startsWith('#') ? preset.value : color); }}><ChevronDown size={14} /></button></div>) : <div className="empty-preset"><span>+</span><p>Your saved presets will live here.</p></div>}</div><div className="palette-title"><h3>Recent colors</h3><button className="text-button" onClick={randomColor}><Sparkles size={14} /> Generate palette</button></div><div className="recent-row">{(recent.length ? recent : [color, '#E8E9FF', '#FDF0E7', '#19202A']).map((item, index) => <button className="recent" key={`${item}-${index}`} style={{ background: item }} onClick={() => updateColor(item)} title={item}><span>{item}</span></button>)}</div></section>
    {copied && copied !== 'css' && <div className="toast"><Check size={15} /> Copied</div>}
  </main>;
}
